openapi: 3.0.0
info:
  title: simple api function
  version: v1
paths:
  /:
    post:
      summary: Echo the request data
      description: Returns the incoming request data as part of the response
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: integer
                    example: 200
                  body:
                    type: string
                    example: "Response from AWS Lambda. Here's the request you just sent me: {\"key\":\"value\"}"

